gantt
    title High-level plan
    dateFormat  YYYY-MM-DD

    section Team
    Hiring :2019-11-15, 30d
    Ramp-up :2019-12-01, 31d

    section No parallel work
    QD Decommission - Getting it to Market :2020-01-01,91d
    DataMIG and UAT :2020-04-01, 61d
    Booking Transactions - Getting it to Market : 2020-04-01, 91d
    DataMIG and UAT :61d

    section Parallel work
    QD Decommission - Getting it to Market :2020-01-01,91d
    Data migration and UAT :2020-04-01, 61d
    Booking Transactions - Getting it to Market : 2020-01-01, 121d
    Data migration and UAT :2020-05-01, 61d
