gantt
    title No parallel work plan
    dateFormat  YYYY-MM-DD
    section Team
    Hiring :2019-11-15, 30d
    Ramp-up :2019-12-01, 31d
    section QD Removal
    Getting it to Market :91d
    Data migration and UAT :2020-04-01, 60d
    section Handle Bookings
    Getting it to Market : 2020-04-01, 91d
    Data migration and UAT :60d
