services:
    Clogger\Middleware\Context\ContextMiddleware: ~
    Clogger\Middleware\Exception\ExceptionCodeMiddleware: ~
    Clogger\Middleware\Exception\ExceptionSimpleMessageMiddleware: ~
    Clogger\Middleware\Exception\StackTraceMiddleware: ~
    App\Helper\Logger\LoggableEventMiddleware: ~

    Clogger\MiddlewareStack:
        arguments:
            - '@Clogger\Middleware\Context\ContextMiddleware'
            - '@App\Helper\Logger\LoggableEventMiddleware'
            - '@Clogger\Middleware\Exception\StackTraceMiddleware'
            - '@Clogger\Middleware\Exception\ExceptionCodeMiddleware'
            - '@Clogger\Middleware\Exception\ExceptionSimpleMessageMiddleware'

    logger:
        class: Clogger\Clogger
        arguments:
            - '@monolog.logger'
            - '@Clogger\MiddlewareStack'
