security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory:
            memory:
                users:
                    admin: { password: '%env(USER_ADMIN_PASSWORD)%', roles: ['ROLE_ADMIN'] }
                    booking: { password: '%env(USER_BOOKING_PASSWORD)%', roles: ['ROLE_BOOKING'] }
                    eai: { password: '%env(USER_EAI_PASSWORD)%', roles: ['ROLE_EAI'] }
    encoders:
        Symfony\Component\Security\Core\User\User: 'plaintext'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: users_in_memory
            stateless: true
            http_basic:
                realm: Restricted

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/internal, roles: ROLE_ADMIN }
         - { path: ^/booking, roles: ROLE_BOOKING }
         - { path: ^/broadcast-listener, roles: ROLE_EAI }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_BOOKING, ROLE_EAI]
