title: Product
type: object
x-tags:
  - products
description: Products are generic entities with a lot of meaning in Smartbox
x-examples:
  41b65e0f-99e2-4608-b9fd-86b57cfe09e5:
    value:
      uuid: 49e60a98-fd4b-4e26-88c8-027818691faf
      external_id: '667834762'
      created_at: '2019-08-26 14:31:23'
      update_at: '2019-08-26 14:31:23'
properties:
  uuid:
    type: string
  external_id:
    type: string
  name:
    type: string
  description:
    type: string
  universe:
    type: string
  is_sellable:
    type: boolean
  is_reservable:
    type: boolean
  partner_external_id:
    type: string
  created_at:
    type: string
    format: date
  updated_at:
    type: string
    format: date
required:
  - external_id
  - name
  - universe
  - is_sellable
  - is_reservable
