title: Product
type: object
x-tags:
  - products
properties:
  uuid:
    type: string
  external_id:
    type: string
  created_at:
    type: string
    format: date
  updated_at:
    type: string
    format: date
x-examples:
  41b65e0f-99e2-4608-b9fd-86b57cfe09e5:
    value:
      uuid: 49e60a98-fd4b-4e26-88c8-027818691faf
      external_id: '667834762'
      created_at: '2019-08-26 14:31:23'
      update_at: '2019-08-26 14:31:23'
description: Products are generic entities with a lot of meaning in Smartbox
