graph LR

subgraph CMs
BB8 -->|A&P|CMHub
YieldPlanet -->|A&P|CMHub
CM[...] -->|A&P|CMHub
CMHub -->|Bookings| BB8
CMHub -->|Bookings|YieldPlanet
CMHub -->|Bookings|CM
end

subgraph "A&P Engine"
R2D2
end

subgraph "Unity3"
JB[JarvisBooking] -->|Bookings| R2D2
R2D2 -->|A&P| JB
end

subgraph "Data Owners"
PRM -->|Partners| EAI
PIM -->|Products| EAI
R2D2 -->|Bookings| EAI
EAI -->|A&P| R2D2
EAI -->|Products| R2D2
EAI -->|Partners| R2D2
EAI -->|Partners| CMHub
EAI --> |Bookings| CMHub
CMHub -->|A&P| EAI
end

style PIM fill:white,stroke:purple,stroke-width:2px
style PRM fill:white,stroke:green,stroke-width:2px
style BB8 fill:white,stroke:red,stroke-width:2px
style YieldPlanet fill:white,stroke:red,stroke-width:2px
style CM fill:white,stroke:red,stroke-width:2px
style JB fill:white,stroke:blue,stroke-width:2px
style EAI fill:lightgray,stroke:black,stroke-width:2px
style R2D2 fill:lightgray,stroke:black,stroke-width:2px
style CMHub fill:lightgray,stroke:black,stroke-width:2px

linkStyle 0 stroke:red,stroke-width:2px;
linkStyle 1 stroke:red,stroke-width:2px;
linkStyle 2 stroke:red,stroke-width:2px;
linkStyle 3 stroke:blue,stroke-width:2px;
linkStyle 4 stroke:blue,stroke-width:2px;
linkStyle 5 stroke:blue,stroke-width:2px;
linkStyle 6 stroke:blue,stroke-width:2px;
linkStyle 7 stroke:red,stroke-width:2px;
linkStyle 8 stroke:green,stroke-width:2px;
linkStyle 9 stroke:purple,stroke-width:2px;
linkStyle 10 stroke:blue,stroke-width:2px;
linkStyle 11 stroke:red,stroke-width:2px;
linkStyle 12 stroke:purple,stroke-width:2px;
linkStyle 13 stroke:green,stroke-width:2px;
linkStyle 14 stroke:green,stroke-width:2px;
linkStyle 15 stroke:blue,stroke-width:2px;
linkStyle 16 stroke:red,stroke-width:2px;
