graph LR

subgraph CMs
BB8 -->|"[Push] A&P"|CMHub
CM1 -->|"[Pull] A&P"|CMHub
CM2 -->|"[Pull] A&P"|CMHub
CM[...] -->|"[Push/Pull] A&P"|CMHub
CMHub -->|"[Push] Bookings"| BB8
CMHub -->|"[Pull] Bookings"| CM1
CMHub -->|"[Pull] Bookings"| CM2
CMHub -->|"[Pull/Push] Bookings"| CM
end

subgraph A&P&B Engine
R2D2
end

subgraph Web
JB[JarvisBooking] -->|"[Push] Bookings"| R2D2
R2D2 -->|"[Get] Enhanced A&P"| JB
end

subgraph Data Owners
PRM -->|"[Push] Partners"| EAI
PIM -->|"[Push] Products"| EAI
R2D2 -->|"[Push] Bookings"| CMHub
EAI -->|"[Push] A&P"| R2D2
EAI -->|"[Broadcast] Products"| R2D2
EAI -->|"[Broadcast] Partners"| R2D2
EAI -->|"[Broadcast] Partners"| CMHub
EAI -->|"[Broadcast] Partners"| BB8
CMHub -->|"[Push] A&P"| EAI
R2D2 -->|"[Push] Rooms"| CMHub
end

style PIM fill:white,stroke:purple,stroke-width:4px
style PRM fill:white,stroke:green,stroke-width:4px
style BB8 fill:white,stroke:red,stroke-width:4px
style CM1 fill:white,stroke:red,stroke-width:4px
style CM2 fill:white,stroke:red,stroke-width:4px
style JB fill:white,stroke:blue,stroke-width:4px
style EAI fill:lightgray,stroke:black,stroke-width:4px
style R2D2 fill:lightgray,stroke:black,stroke-width:4px
style CMHub fill:lightgray,stroke:black,stroke-width:4px

linkStyle 0 stroke:red,stroke-width:4px;
linkStyle 1 stroke:red,stroke-width:4px,stroke-dasharray:5,5;
linkStyle 2 stroke:red,stroke-width:4px,stroke-dasharray:5,5;
linkStyle 3 stroke:red,stroke-width:4px,stroke-dasharray:5,5,opacity:0.3;
linkStyle 4 stroke:blue,stroke-width:4px;
linkStyle 5 stroke:blue,stroke-width:4px,stroke-dasharray:5,5;
linkStyle 6 stroke:blue,stroke-width:4px,stroke-dasharray:5,5;
linkStyle 7 stroke:blue,stroke-width:4px,stroke-dasharray:5,5,opacity:0.3;
linkStyle 8 stroke:blue,stroke-width:4px;
linkStyle 9 stroke:red,stroke-width:4px;
linkStyle 10 stroke:green,stroke-width:4px;
linkStyle 11 stroke:purple,stroke-width:4px;
linkStyle 12 stroke:blue,stroke-width:4px;
linkStyle 13 stroke:red,stroke-width:4px;
linkStyle 14 stroke:purple,stroke-width:4px,stroke-dasharray:5,5;
linkStyle 15 stroke:green,stroke-width:4px,stroke-dasharray:5,5;
linkStyle 16 stroke:green,stroke-width:4px,stroke-dasharray:5,5;
linkStyle 17 stroke:green,stroke-width:4px,stroke-dasharray:5,5;
linkStyle 18 stroke:red,stroke-width:4px;
linkStyle 19 stroke:brown,stroke-width:4px;
