graph TD

subgraph Check R2D2 Availability
  CurrentR2D2Availability --> TemporaryBookingsCalculation{HasNonExpiredTemporaryBooking}
  TemporaryBookingsCalculation --> |No| AvailabilityWithTemporaryBookingsCalculated
  TemporaryBookingsCalculation --> |Yes| ReduceAvailabilityWithTemporaryBookings
  ReduceAvailabilityWithTemporaryBookings --> AvailabilityWithTemporaryBookingsCalculated
  AvailabilityWithTemporaryBookingsCalculated --> NewBookingsBookingsCalculation{HasNewConfirmedBooking}

  NewBookingsBookingsCalculation --> |No| AvailabilityWithNewBookingsCalculated
  NewBookingsBookingsCalculation --> |Yes| ReduceAvailabilityWithNewBookings
  ReduceAvailabilityWithNewBookings --> AvailabilityWithNewBookingsCalculated
  AvailabilityWithNewBookingsCalculated --> ReturnNewR2D2Availability
end

subgraph Booking Life Cycle
  TemporaryBookingRequest --> CheckR2D2Availability{CheckR2D2Availability}
  CheckR2D2Availability --> |Yes| CreatesNewTemporaryBooking
  CreatesNewTemporaryBooking --> TemporaryBooking
  CheckR2D2Availability --> |No| RejectsBooking

  TemporaryBooking --> ExpiredBooking
  ExpiredBooking --> |Confirm Expired Temp Booking| TemporaryBookingRequest

  TemporaryBooking --> |Confirm Temp Booking| ConfirmedBooking
  ConfirmedBooking --> CalculateAvailability

  ConfirmedBooking --> |Cancel Booking| CancelledBooking
  CancelledBooking --> CalculateAvailability

  CalculateAvailability --> SetNewR2D2Availability
end
