graph LR
subgraph "R2D2-API"
LBBE{API Load Balancer fa:fa-asterisk} --- PHP1[PHP Node 1 fa:fa-server <br>NGINX + PHP-FPM + R2D2 Code + R2D2 .env]
LBBE --- PHP2[PHP Node 2 fa:fa-server <br>NGINX + PHP-FPM + R2D2 Code + R2D2 .env]
PHP1 --- RC[REDIS CACHE fa:fa-cube]
PHP2 --- RC
PHPN[PHP Node N fa:fa-server] --- RC
RC --- DBM[DB Master fa:fa-database]
DBM --- DBS[DB Slave fa:fa-database]
PHP1 --- R[REDIS SESSION fa:fa-cube]
PHP2 --- R
PHPN --- R
PHP1 --- RQ[REDIS QUEUE fa:fa-cube]
PHP2 --- RQ
PHPN --- RQ
end

subgraph "CMHub API"
CMHub[CMHub fa:fa-arrows-alt] --- XCMA[External CM fa:fa-cloud]
CMHub --- XCMB[External CM fa:fa-cloud]
CMHub --- LBBE
end
