variables:
  BASE_IMAGE: docker-registry.production.smartbox.com/millenium-falcon/r2d2-base
  BASE_IMAGE_VERSION: 0.0.11
  BASE_FULL_IMAGE: ${BASE_IMAGE}:${BASE_IMAGE_VERSION}

build-base-image:
  stage: Build base image
  image: docker:dind
  only:
    - CI-master
  tags:
    - k8s-alpha
  script:
    - >
      docker build --pull
      --tag ${BASE_IMAGE}:${BASE_IMAGE_VERSION}
      --tag ${BASE_IMAGE}:latest .ci/docker/base
    - docker push ${BASE_IMAGE}:${BASE_IMAGE_VERSION}
    - docker push ${BASE_IMAGE}:latest
