phpstan:
  stage: Static analysis
  image: ${BASE_FULL_IMAGE}
  needs:
    - composer
  script:
    - vendor/bin/phpstan analyse $(pwd)/src --level 8
  tags:
    - k8s

php-cs-fixer:
  stage: Static analysis
  image: ${BASE_FULL_IMAGE}
  needs:
    - composer
  script:
    - vendor/bin/php-cs-fixer fix -v --dry-run
  tags:
    - k8s

phpmetrics:
  stage: Static analysis
  image: ${BASE_FULL_IMAGE}
  needs:
    - composer
  script:
    - vendor/bin/phpmetrics --report-html=report/html/phpmetrics src
  artifacts:
    expire_in: 3 days
    paths:
      - report/
  tags:
    - k8s

psalm:
  stage: Static analysis
  image: ${BASE_FULL_IMAGE}
  needs:
    - composer
  script:
    - vendor/bin/psalm
  tags:
    - k8s

