title: ProductRelationship
type: object
x-tags:
  - products
  - boxes
  - experiences
  - components
description: Products Relationships are explicity relations between different products
x-examples:
  product-relationship-01:
    value:
      uuid: dbdec460-d868-4cbd-9f25-da88946986fc
      parent_product:
        golden_id: PRODUCT 01
      child_product:
        golden_id: PRODUCT 02
      is_enabled: true
properties:
  uuid:
    type: string
    description: Product Relationship UUID
    format: uuid
  parent_product:
    $ref: ./product.v1.yaml
  child_product:
    $ref: ./product.v1.yaml
  is_enabled:
    type: boolean
    description: Product is enabled
  relationship_type:
    type: string
    enum:
      - Box-Experience
      - Experience-Component
      - Concept
      - Kit
    description: Type of the relationship
  created_at:
    type: string
    description: Date of entity creation in R2D2
    format: date-time
  updated_at:
    type: string
    description: Date of entity update in R2D2
    format: date-time
required:
  - parent_product
  - child_product
  - is_enabled
  - relationship_type
