title: Product
type: object
x-tags:
  - products
description: 'Products are generic entities with a lot of meaning in Smartbox, in R2D2 they will be mapped to boxes, experiences or room components.'
x-examples:
  product-01:
    value:
      golden_id: '123456789'
      name: This is a product
      description: This is a product description
      universe: STAY
      is_sellable: true
      is_reservable: true
      partner_golden_id: 123456789
properties:
  uuid:
    type: string
    description: Product UUID
    format: uuid
  golden_id:
    type: string
    description: Product Golden ID
  name:
    type: string
    description: Product name
  description:
    type: string
    description: Product description
  universe:
    type: string
    description: Product universe (main category)
  is_sellable:
    type: boolean
    description: Product is sellable (upsellable in case of room components)
  is_reservable:
    type: boolean
    description: Product is reservable (if a component is a room component)
  partner_golden_id:
    type: string
    description: Partner Golden ID
  created_at:
    type: string
    description: Date of entity creation in R2D2
    format: date-time
  updated_at:
    type: string
    description: Date of entity update in R2D2
    format: date-time
required:
  - golden_id
