version: '3.4'

x-service-template: &service-template
  image: "${APP_IMAGE}"
  env_file:
    - "${ENV_FILE}"
  volumes:
    - /var/log/jarvis/:/app/var/log/

x-worker-template: &worker-template
  <<: *service-template
  deploy:
    replicas: 2
  command: ['/app/bin/start-command.sh']

services:
  api:
    <<: *service-template
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
    deploy:
      mode: global
      update_config:
        order: start-first
    stop_grace_period: 10s

  cron:
    <<: *service-template
    command: ['/app/bin/start-crond.sh']

  worker-broadcast-listeners-partner:
    <<: *worker-template
    environment:
      QUEUES: broadcast-listeners-partner

  worker-broadcast-listeners-product:
    <<: *worker-template
    environment:
      QUEUES: broadcast-listeners-product

  worker-broadcast-listeners-price-information:
    <<: *worker-template
    environment:
      QUEUES: broadcast-listeners-price-information

  worker-broadcast-listeners-product-relationship:
    <<: *worker-template
    environment:
      QUEUES: broadcast-listeners-product-relationship
    deploy:
      replicas: 6

  worker-calculate-manageable-flag:
    <<: *worker-template
    environment:
      QUEUES: calculate-manageable-flag
    deploy:
      replicas: 10

  worker-push-room-information:
    <<: *worker-template
    environment:
      QUEUES: push-room-information

  worker-listener-room-availability:
    <<: *worker-template
    environment:
      QUEUES: listener-room-availability

  worker-listener-room-availability-list:
    <<: *worker-template
    environment:
      QUEUES: listener-room-availability-list

  worker-listener-room-price:
    <<: *worker-template
    environment:
      QUEUES: listener-room-price

  worker-listener-room-price-list:
    <<: *worker-template
    environment:
      QUEUES: listener-room-price-list

  calculate-flat-manageable-component:
    <<: *worker-template
    environment:
      QUEUES: calculate-flat-manageable-component
    deploy:
      replicas: 10
